"use client";
import { useEffect, useMemo, useRef, useState } from "react";
import { CalendarDays, ChevronLeft, ChevronRight, Check, Circle, Clock3, Plus, Search, Upload, Sparkles, LayoutDashboard, ListTodo, FolderKanban, BarChart3, Settings, Bell, Paperclip, MoreHorizontal, ArrowUpRight, X, FileText, Link2, BookOpen, Image as ImageIcon, Github, Cloud, MessageCircle, Zap, Target, Calendar, CheckCircle2 } from "lucide-react";

type Task={id:number;title:string;project:string;date:string;start:string;end:string;progress:number;attachments:string[];description:string;done?:boolean};
const today=new Date(); const iso=(d:Date)=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;
const dateLabel=(d:Date)=>d.toLocaleDateString("en-US",{weekday:"long",month:"long",day:"numeric"});
const initial:Task[]=[
{id:1,title:"Review production Python roadmap",project:"Learning",date:iso(today),start:"07:30",end:"09:00",progress:60,attachments:["Roadmap notes","Course link"],description:"Work through the current week's learning objectives and capture key takeaways."},
{id:2,title:"Build schedule dashboard interface",project:"ANGEL",date:iso(today),start:"09:30",end:"11:30",progress:35,attachments:["GitHub repository"],description:"Implement the core daily and weekly planning experience."},
{id:3,title:"Study system design fundamentals",project:"Learning",date:iso(today),start:"12:00",end:"13:30",progress:0,attachments:[],description:"Read and summarize the next chapter."},
{id:4,title:"Attention Firewall — review next milestone",project:"Attention Firewall",date:iso(today),start:"15:00",end:"17:00",progress:20,attachments:["Project brief","GitHub"],description:"Check current progress, resolve open questions, and plan the next build."},
{id:5,title:"Write weekly reflection",project:"Personal",date:iso(today),start:"19:00",end:"19:30",progress:0,attachments:[],description:"Record wins, blockers, and priorities for tomorrow."},
{id:6,title:"Plan ANGEL product milestones",project:"ANGEL",date:iso(new Date(today.getTime()+86400000)),start:"08:00",end:"10:00",progress:0,attachments:["Product notes"],description:"Define the next milestones and acceptance criteria."},
{id:7,title:"Complete Python practice exercises",project:"Learning",date:iso(new Date(today.getTime()+86400000)),start:"11:00",end:"12:30",progress:0,attachments:[],description:"Apply the concepts from the lesson."},
{id:8,title:"Review project backlog",project:"Attention Firewall",date:iso(new Date(today.getTime()+2*86400000)),start:"16:00",end:"17:00",progress:0,attachments:[],description:"Prioritize the next development tasks."}
];
const mins=(t:string)=>{const [h,m]=t.split(":").map(Number);return h*60+m};
const period=(t:string)=>{const n=mins(t);return n<420?"Early morning":n<660?"Morning":n<840?"Mid-day":"Evening"};
const pctColor=(p:number)=>p===0?"#e34e4e":p===10?"#a5a9b0":`hsl(${Math.round(120*(p/100))} 58% 42%)`;
export default function Home(){
 const [tasks,setTasks]=useState<Task[]>(initial),[view,setView]=useState<"day"|"week"|"month">("day"),[selected,setSelected]=useState(iso(today)),[active,setActive]=useState<Task|null>(null),[query,setQuery]=useState(""),[showAdd,setShowAdd]=useState(false),[showImport,setShowImport]=useState(false),[newTitle,setNewTitle]=useState(""),[newStart,setNewStart]=useState("08:00"),[newEnd,setNewEnd]=useState("09:00"),[newProject,setNewProject]=useState("Personal"),[notice,setNotice]=useState(""),[aiPrompt,setAiPrompt]=useState("");
 const fileRef=useRef<HTMLInputElement>(null);
 const [importing,setImporting]=useState(false);
 useEffect(()=>{try{const saved=localStorage.getItem("angel.tasks.v1");if(saved)setTasks(JSON.parse(saved));}catch{}},[]);
 useEffect(()=>{try{localStorage.setItem("angel.tasks.v1",JSON.stringify(tasks));}catch{}},[tasks]);
 const date=new Date(selected+"T12:00:00");
 const filtered=useMemo(()=>tasks.filter(t=>t.date===selected&&t.title.toLowerCase().includes(query.toLowerCase())),[tasks,selected,query]);
 const grouped=["Early morning","Morning","Mid-day","Evening"];
 const week=Array.from({length:7},(_,i)=>{const d=new Date(date);d.setDate(date.getDate()-((date.getDay()+6)%7)+i);return d});
 const monthStart=new Date(date.getFullYear(),date.getMonth(),1), monthDays=new Date(date.getFullYear(),date.getMonth()+1,0).getDate(), offset=(monthStart.getDay()+6)%7;
 const changeProgress=(id:number,p:number)=>setTasks(prev=>prev.map(t=>t.id===id?{...t,progress:p,done:p===100}:t));
 const shift=(n:number)=>{const d=new Date(date);d.setDate(d.getDate()+n);setSelected(iso(d));};
 const importFile=async(file:File)=>{setImporting(true);try{const form=new FormData();form.append("file",file);const res=await fetch("/api/import",{method:"POST",body:form});const data=await res.json();if(!res.ok)throw new Error(data.error||"Import failed");const rows=data.tasks||[];if(!rows.length)throw new Error("No task rows detected. Use a spreadsheet with task/date/start/end columns, or clear task lines in a document.");const added:Task[]=rows.map((t:any,i:number)=>({id:Date.now()+i,title:t.title,project:t.project||"Imported",date:t.date||selected,start:t.start||"09:00",end:t.end||"10:00",progress:0,attachments:[file.name],description:t.description||"Imported from schedule."}));setTasks(prev=>[...prev,...added]);setNotice("Imported "+added.length+" tasks. Review the detected dates and times.");setShowImport(false);}catch(e){setNotice(e instanceof Error?e.message:"Import failed.");}finally{setImporting(false);}};
 const addTask=()=>{if(!newTitle.trim())return;setTasks(prev=>[...prev,{id:Date.now(),title:newTitle,project:newProject,date:selected,start:newStart,end:newEnd,progress:0,attachments:[],description:""}]);setNewTitle("");setShowAdd(false);};
 const total=tasks.filter(t=>t.date===selected).length, completed=tasks.filter(t=>t.date===selected&&t.progress===100).length, avg=total?Math.round(tasks.filter(t=>t.date===selected).reduce((a,t)=>a+t.progress,0)/total):0;
 return <main className="shell">
 <aside className="sidebar"><div className="brand"><div className="brand-mark">A</div><span>angel<span className="brand-dot">.</span></span></div><div className="workspace"><div className="avatar">N</div><div><b>My workspace</b><small>Personal account</small></div><ChevronRight size={15}/></div>
 <div className="nav-label">WORKSPACE</div><nav><button className="nav-item active"><LayoutDashboard size={17}/> Overview</button><button className="nav-item" onClick={()=>setView("day")}><ListTodo size={17}/> My tasks</button><button className="nav-item" onClick={()=>setView("week")}><CalendarDays size={17}/> Calendar</button><button className="nav-item"><FolderKanban size={17}/> Projects <span className="nav-count">4</span></button><button className="nav-item"><BarChart3 size={17}/> Insights</button></nav>
 <div className="nav-label integration-label">CONNECTED WORK</div><nav><button className="nav-item"><Github size={17}/> GitHub <span className="connect-dot"/></button><button className="nav-item"><Cloud size={17}/> Google Drive <span className="connect-dot muted"/></button><button className="nav-item"><MessageCircle size={17}/> Social accounts</button></nav>
 <div className="sidebar-bottom"><div className="upgrade"><div className="upgrade-icon"><Sparkles size={16}/></div><b>Make every day count</b><p>Let your AI planner help you focus on what matters.</p><button onClick={()=>document.getElementById("ai-panel")?.scrollIntoView({behavior:"smooth"})}>Explore AI planner <ArrowUpRight size={14}/></button></div><button className="nav-item"><Settings size={17}/> Settings</button><div className="profile"><div className="avatar">N</div><div><b>Narlod</b><small>Personal plan</small></div><MoreHorizontal size={18}/></div></div>
 </aside>
 <section className="main"><header className="topbar"><div className="crumb">Workspace <span>/</span> <b>Overview</b></div><div className="top-actions"><div className="search"><Search size={15}/><input placeholder="Search tasks..." value={query} onChange={e=>setQuery(e.target.value)}/><kbd>⌘ K</kbd></div><button className="icon-btn"><Bell size={17}/><i/></button><div className="avatar small-avatar">N</div></div></header>
 <div className="content"><div className="welcome-row"><div><div className="eyebrow"><span className="live-dot"/> YOUR PERSONAL COMMAND CENTER</div><h1>Make today <em>count.</em></h1><p className="subheading">A clear plan. Meaningful progress. One day at a time.</p></div><button className="primary" onClick={()=>setShowAdd(true)}><Plus size={17}/> Add a task</button></div>
 <div className="stats"><div className="stat-card"><div className="stat-head"><span>Today's tasks</span><div className="stat-icon blue"><ListTodo size={17}/></div></div><div className="stat-number">{total}<small> tasks</small></div><div className="stat-foot">{completed} completed <span>·</span> {total-completed} remaining</div></div><div className="stat-card"><div className="stat-head"><span>Daily progress</span><div className="stat-icon green"><Target size={17}/></div></div><div className="stat-number">{avg}<small>%</small></div><div className="mini-track"><div style={{width:avg+"%"}}/></div></div><div className="stat-card"><div className="stat-head"><span>Focus time planned</span><div className="stat-icon amber"><Clock3 size={17}/></div></div><div className="stat-number">{(tasks.filter(t=>t.date===selected).reduce((a,t)=>a+mins(t.end)-mins(t.start),0)/60).toFixed(1)}<small> hrs</small></div><div className="stat-foot">Across {total} scheduled blocks</div></div><div className="stat-card"><div className="stat-head"><span>Consistency</span><div className="stat-icon violet"><Zap size={17}/></div></div><div className="stat-number">—<small> days</small></div><div className="stat-foot">Build your first streak</div></div></div>
 <div className="planner-head"><div><div className="section-title">Your schedule</div><p className="section-sub">Stay intentional with your time.</p></div><div className="view-switch"><button className={view==="day"?"chosen":""} onClick={()=>setView("day")}>Day</button><button className={view==="week"?"chosen":""} onClick={()=>setView("week")}>Week</button><button className={view==="month"?"chosen":""} onClick={()=>setView("month")}>Month</button></div></div>
 <div className="calendar-bar"><div className="date-controls"><button className="arrow" onClick={()=>shift(view==="month"?-30:view==="week"?-7:-1)}><ChevronLeft size={17}/></button><button className="date-title" onClick={()=>setSelected(iso(today))}>{view==="month"?date.toLocaleDateString("en-US",{month:"long",year:"numeric"}):view==="week"?`Week of ${week[0].toLocaleDateString("en-US",{month:"short",day:"numeric"})}`:dateLabel(date)}</button><button className="arrow" onClick={()=>shift(view==="month"?30:view==="week"?7:1)}><ChevronRight size={17}/></button></div><button className="today-btn" onClick={()=>setSelected(iso(today))}>Today</button></div>
 {view==="day"&&<div className="day-view">{grouped.map((g,i)=>{const list=filtered.filter(t=>period(t.start)===g).sort((a,b)=>mins(a.start)-mins(b.start));return <section className="period" key={g}><div className="period-label"><div className={`period-dot p${i}`}/><div><b>{g}</b><small>{["12:00 AM – 7:00 AM","7:00 AM – 11:00 AM","11:00 AM – 2:00 PM","3:00 PM – 12:00 AM"][i]}</small></div><span className="period-count">{list.length}</span></div><div className="period-tasks">{list.length===0?<div className="empty-period">No tasks planned</div>:list.map(t=><TaskCard key={t.id} task={t} onOpen={()=>setActive(t)} onProgress={p=>changeProgress(t.id,p)}/>)}</div></section>})}<button className="add-inline" onClick={()=>setShowAdd(true)}><Plus size={15}/> Add task to this day</button></div>}
 {view==="week"&&<div className="week-grid">{week.map(d=>{const key=iso(d),list=tasks.filter(t=>t.date===key);return <button className={`week-day ${key===selected?"week-selected":""}`} key={key} onClick={()=>{setSelected(key);setView("day")}}><span>{d.toLocaleDateString("en-US",{weekday:"short"})}</span><b>{d.getDate()}</b><small>{list.length} tasks</small><div className="week-dots">{list.slice(0,4).map(t=><i key={t.id} style={{background:pctColor(t.progress)}}/>)}</div></button>})}</div>}
 {view==="month"&&<div className="month-wrap"><div className="month-grid">{["Mon","Tue","Wed","Thu","Fri","Sat","Sun"].map(x=><div className="month-weekday" key={x}>{x}</div>)}{Array.from({length:offset},(_,i)=><div className="month-cell blank" key={"b"+i}/>)}{Array.from({length:monthDays},(_,i)=>{const d=new Date(date.getFullYear(),date.getMonth(),i+1),key=iso(d),list=tasks.filter(t=>t.date===key),avg=list.length?Math.round(list.reduce((a,t)=>a+t.progress,0)/list.length):0,done=list.filter(t=>t.progress===100).length;return <button key={key} className={`month-cell ${key===selected?"month-selected":""} ${key===iso(today)?"is-today":""}`} onClick={()=>{setSelected(key);setView("day")}}><span className="month-date">{i+1}</span>{list.length>0&&<><span className="month-taskcount">{list.length} tasks</span><div className="month-progress"><i style={{width:avg+"%",background:pctColor(avg)}}/></div><small><b className="positive">+{done}</b> / <b className="negative">-{list.length-done}</b></small><small className="month-pct">{avg}% done</small></>}</button>})}</div><div className="month-legend"><span><i className="positive-dot"/> Completed</span><span><i className="negative-dot"/> Pending</span><span>Percentage reflects average task progress</span></div></div>}
 <div className="lower-grid"><section className="panel" id="ai-panel"><div className="panel-heading"><div className="ai-badge"><Sparkles size={16}/></div><div><b>AI daily briefing</b><small>Your planning copilot</small></div><span className="coming">PREVIEW</span></div><div className="briefing"><div className="briefing-greeting">A little direction goes a long way.</div><p>{total===0?"Your day is open. Add a task or import your schedule to get a tailored plan.":`You have ${total} tasks planned today, with ${completed} fully completed. ${avg<50?"Consider starting with one focused, high-impact task and protecting time to finish it.":"Keep your momentum: review the remaining tasks and choose the next achievable step."}`}</p><div className="suggestion"><div className="suggestion-icon"><Zap size={15}/></div><span><b>Suggested next step</b><small>{filtered.filter(t=>t.progress<100).sort((a,b)=>mins(a.start)-mins(b.start))[0]?.title||"Add your next priority"} </small></span></div></div><form className="ai-input" onSubmit={e=>{e.preventDefault();setNotice("AI chat interface is a preview. Connect an AI provider to enable personalized responses.");setAiPrompt("")}}><input placeholder="Ask your planner anything..." value={aiPrompt} onChange={e=>setAiPrompt(e.target.value)}/><button aria-label="Send prompt"><ArrowUpRight size={17}/></button></form></section>
 <section className="panel integrations"><div className="panel-heading"><div className="integration-symbol"><FolderKanban size={16}/></div><div><b>Connected workspace</b><small>Bring your work together</small></div></div>{[{icon:<Github size={17}/>,name:"GitHub projects",desc:"Track repository progress"},{icon:<Cloud size={17}/>,name:"Google Drive",desc:"Find learning and writing materials"},{icon:<MessageCircle size={17}/>,name:"Social channels",desc:"Plan posts and manage replies"}].map(x=><div className="integration-row" key={x.name}><div className="integration-icon">{x.icon}</div><div><b>{x.name}</b><small>{x.desc}</small></div><button onClick={()=>setNotice("Integration setup will be available after secure account authorization is implemented.")}>Connect <Plus size={13}/></button></div>)}</section></div>
 <div className="import-strip"><div className="import-icon"><Upload size={18}/></div><div><b>Already have a schedule?</b><p>Import an Excel, Word, or PDF file and turn it into an organized plan.</p></div><button onClick={()=>setShowImport(true)}>Import schedule <ArrowUpRight size={15}/></button></div>
 <footer>ANGEL <span>·</span> Plan with purpose <span className="footer-right">Your plans, your pace.</span></footer>
 </div></section>
 {active&&<div className="overlay" onMouseDown={e=>{if(e.target===e.currentTarget)setActive(null)}}><div className="detail-modal"><div className="modal-top"><span className="modal-tag">{active.project}</span><button className="close" onClick={()=>setActive(null)}><X size={18}/></button></div><h2>{active.title}</h2><p className="detail-time"><Clock3 size={15}/> {active.start} – {active.end} · {dateLabel(new Date(active.date+"T12:00:00"))}</p><p className="detail-desc">{active.description||"No description yet. Add context to make this task easier to execute."}</p><div className="detail-progress"><div className="detail-progress-head"><b>Task progress</b><strong>{active.progress}%</strong></div><ProgressBar value={active.progress}/><div className="checkin-label">CHECK IN — SELECT YOUR PROGRESS</div><div className="progress-choices">{Array.from({length:11},(_,i)=><button key={i} className={active.progress===i*10?"pct-active":""} onClick={()=>{changeProgress(active.id,i*10);setActive({...active,progress:i*10})}}>{i*10}</button>)}</div></div><div className="materials-head"><div><b>Task materials</b><small>Links, notes, books, and images for this task</small></div><button className="add-material" onClick={()=>setNotice("Material attachment editor is coming in the next build.")}><Plus size={14}/> Add</button></div><div className="materials">{active.attachments.length?active.attachments.map((a,i)=><div className="material" key={i}><FileText size={16}/><span>{a}</span><MoreHorizontal size={16}/></div>):<div className="no-material">No materials attached yet.</div>}</div><button className="modal-done" onClick={()=>setActive(null)}>Done</button></div></div>}
 {showAdd&&<div className="overlay"><form className="form-modal" onSubmit={e=>{e.preventDefault();addTask()}}><div className="modal-top"><h2>New task</h2><button type="button" className="close" onClick={()=>setShowAdd(false)}><X size={18}/></button></div><label>Task name<input required autoFocus value={newTitle} onChange={e=>setNewTitle(e.target.value)} placeholder="What do you want to accomplish?"/></label><label>Project<input value={newProject} onChange={e=>setNewProject(e.target.value)}/></label><div className="form-row"><label>Start time<input type="time" value={newStart} onChange={e=>setNewStart(e.target.value)}/></label><label>Deadline<input type="time" value={newEnd} onChange={e=>setNewEnd(e.target.value)}/></label></div><button className="primary submit" type="submit">Create task</button></form></div>}
 {showImport&&<div className="overlay"><div className="form-modal"><div className="modal-top"><h2>Import your schedule</h2><button className="close" onClick={()=>setShowImport(false)}><X size={18}/></button></div><div className="dropzone" onClick={()=>fileRef.current?.click()}><Upload size={25}/><b>{importing?"Extracting schedule…":"Choose a file to upload"}</b><span>Excel, Word, or PDF · up to 20 MB</span><button className="secondary" type="button">Browse files</button><input ref={fileRef} type="file" accept=".xlsx,.xls,.csv,.docx,.pdf" hidden onChange={e=>e.target.files?.[0]&&importFile(e.target.files[0])}/></div><p className="import-note">Files are processed by the schedule extractor. Tasks are saved in this browser; verify extracted dates and times.</p></div></div>}
 {notice&&<div className="toast"><span>{notice}</span><button onClick={()=>setNotice("")}><X size={15}/></button></div>}
 </main>
}
function ProgressBar({value}:{value:number}){return <div className="progress-track"><div className="progress-fill" style={{width:value+"%",background:pctColor(value)}}/></div>}
function TaskCard({task,onOpen,onProgress}:{task:Task;onOpen:()=>void;onProgress:(p:number)=>void}){return <div className="task-card"><div className="task-time"><b>{task.start}</b><span>{task.end}</span></div><div className="task-main"><button className="task-title" onClick={onOpen}>{task.title}</button><div className="task-meta"><span className="project-pill">{task.project}</span>{task.attachments.length>0&&<span className="attachment-count"><Paperclip size={12}/>{task.attachments.length}</span>}</div><div className="task-progress-row"><ProgressBar value={task.progress}/><b style={{color:pctColor(task.progress)}}>{task.progress}%</b></div><div className="quick-check"><span>Check in</span><div>{[0,25,50,75,100].map(p=><button key={p} className={task.progress===p?"quick-active":""} onClick={()=>onProgress(p)}>{p}%</button>)}</div></div></div><button className="task-open" onClick={onOpen} aria-label="Open task details"><ChevronRight size={17}/></button></div>}
