'use client';
import { useEffect, useMemo, useState } from 'react';
import { Activity, ArrowLeft, ArrowRight, CalendarDays, Check, CheckCircle2, ChevronDown, Circle, CloudUpload, Compass, LayoutDashboard, ListTodo, Plus, Search, Sparkles, Target, Trash2, X } from 'lucide-react';

type Task = { id:string; title:string; date:string; time:string; category:string; done:boolean; duration:number };
const pad=(n:number)=>String(n).padStart(2,'0');
const dateKey=(d:Date)=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;
const todayKey=()=>dateKey(new Date());
const starter:Task[]=[
 {id:'seed-1',title:'Morning reset & journaling',date:todayKey(),time:'07:00',category:'Personal',done:true,duration:30},
 {id:'seed-2',title:'Review weekly priorities',date:todayKey(),time:'08:00',category:'Planning',done:true,duration:45},
 {id:'seed-3',title:'Deep work — product strategy',date:todayKey(),time:'09:00',category:'Work',done:false,duration:120},
 {id:'seed-4',title:'Team sync and project updates',date:todayKey(),time:'11:30',category:'Work',done:false,duration:45},
 {id:'seed-5',title:'Lunch & take a proper break',date:todayKey(),time:'13:00',category:'Personal',done:false,duration:60},
 {id:'seed-6',title:'Build sprint: planner foundation',date:todayKey(),time:'14:00',category:'Build',done:false,duration:120},
 {id:'seed-7',title:'Read and capture key insights',date:todayKey(),time:'16:30',category:'Learning',done:false,duration:30}
];
const nav=[{name:'Overview',icon:LayoutDashboard},{name:'My planner',icon:CalendarDays},{name:'Tasks',icon:ListTodo},{name:'My projects',icon:Target},{name:'Focus space',icon:Compass},{name:'Insights',icon:Activity}];
export default function Home(){
 const [tasks,setTasks]=useState<Task[]>([]),[loaded,setLoaded]=useState(false),[view,setView]=useState<'Day'|'Week'|'Month'>('Day'),[active,setActive]=useState('Overview'),[date,setDate]=useState(()=>new Date()),[query,setQuery]=useState(''),[adding,setAdding]=useState(false),[title,setTitle]=useState(''),[time,setTime]=useState('09:00'),[category,setCategory]=useState('Work'),[duration,setDuration]=useState('60'),[toast,setToast]=useState('');
 useEffect(()=>{try{const raw=localStorage.getItem('angel.tasks.v1');if(raw){const parsed=JSON.parse(raw);if(Array.isArray(parsed))setTasks(parsed)}else setTasks(starter)}catch{setTasks(starter)}setLoaded(true)},[]);
 useEffect(()=>{if(loaded){try{localStorage.setItem('angel.tasks.v1',JSON.stringify(tasks))}catch{setToast('Could not save in this browser')}}},[tasks,loaded]);
 const selected=dateKey(date),dayTasks=useMemo(()=>tasks.filter(t=>t.date===selected&&t.title.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>a.time.localeCompare(b.time)),[tasks,selected,query]),done=dayTasks.filter(t=>t.done).length,pct=dayTasks.length?Math.round(done/dayTasks.length*100):0;
 const changeDay=(n:number)=>setDate(d=>{const next=new Date(d);next.setDate(next.getDate()+n);return next});
 const toggle=(id:string)=>setTasks(old=>old.map(t=>t.id===id?{...t,done:!t.done}:t));
 const add=()=>{if(!title.trim())return;setTasks(old=>[...old,{id:crypto.randomUUID(),title:title.trim(),date:selected,time,category,done:false,duration:Math.max(5,Number(duration)||60)}]);setTitle('');setAdding(false);setToast('Task saved to your plan');};
 const remove=(id:string)=>setTasks(old=>old.filter(t=>t.id!==id));
 const weekStart=new Date(date);weekStart.setDate(date.getDate()-((date.getDay()+6)%7));
 const weekDays=Array.from({length:7},(_,i)=>{const d=new Date(weekStart);d.setDate(d.getDate()+i);return d});
 const monthStart=new Date(date.getFullYear(),date.getMonth(),1),gridStart=new Date(monthStart);gridStart.setDate(1-((monthStart.getDay()+6)%7));
 const monthDays=Array.from({length:42},(_,i)=>{const d=new Date(gridStart);d.setDate(gridStart.getDate()+i);return d});
 const taskCount=(key:string)=>tasks.filter(t=>t.date===key).length;
 return <main className="shell"><aside className="sidebar"><div className="brand"><span className="brand-icon"><Sparkles size={18}/></span><b>angel<span>.</span></b></div><div className="workspace"><div className="avatar">N</div><div><b>My workspace</b><small>Personal space</small></div><ChevronDown size={14}/></div><small className="nav-label">WORKSPACE</small>{nav.map(it=><button key={it.name} onClick={()=>setActive(it.name)} className={'nav '+(active===it.name?'selected':'')}><it.icon size={17}/>{it.name}</button>)}<div className="side-bottom"><div className="promo"><Sparkles size={17}/><b>Make room for what matters.</b><p>Your plans, priorities, and progress — in one place.</p></div><div className="user"><div className="avatar">N</div><div><b>Narlod</b><small>Personal account</small></div></div></div></aside>
 <section className="main"><header><div className="crumb">Workspace <span>/</span> <b>{active}</b></div><div className="header-right"><div className="search"><Search size={15}/><input aria-label="Search tasks" placeholder="Search tasks..." value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="avatar">N</div></div></header><div className="content"><div className="welcome"><div><div className="eyebrow">✦ YOUR PERSONAL COMMAND CENTER</div><h1>{active==='Overview'?'Make today count.':active==='Tasks'?'Small steps. Real progress.':active==='Focus space'?'Protect your attention.':'Your time, intentionally.'}</h1><p>{active==='Tasks'?'Review and update the tasks on your selected date.':'A little clarity goes a long way. Here’s your plan.'}</p></div><button className="primary" onClick={()=>setAdding(true)}><Plus size={16}/> New task</button></div>
 <div className="datebar"><div className="datecontrols"><button onClick={()=>setDate(new Date())}>Today</button><button className="arrow" aria-label="Previous period" onClick={()=>changeDay(view==='Day'?-1:view==='Week'?-7:-30)}><ArrowLeft size={14}/></button><button className="arrow" aria-label="Next period" onClick={()=>changeDay(view==='Day'?1:view==='Week'?7:30)}><ArrowRight size={14}/></button><b>{view==='Month'?date.toLocaleDateString('en-US',{month:'long',year:'numeric'}):view==='Week'?weekStart.toLocaleDateString('en-US',{month:'short',day:'numeric'})+' – '+weekDays[6].toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'}):date.toLocaleDateString('en-US',{weekday:'long',month:'long',day:'numeric',year:'numeric'})}</b></div><div className="tabs">{(['Day','Week','Month'] as const).map(v=><button className={view===v?'on':''} onClick={()=>setView(v)} key={v}>{v}</button>)}</div></div>
 <div className="stats"><article><label>Tasks completed</label><strong>{done}<small> / {dayTasks.length}</small></strong><div className="bar"><i style={{width:pct+'%'}}/></div><small>{pct}% of selected day</small></article><article><label>Planned time</label><strong>{Math.floor(dayTasks.reduce((s,t)=>s+t.duration,0)/60)}<small>h {dayTasks.reduce((s,t)=>s+t.duration,0)%60}m</small></strong><small>Across {dayTasks.length} scheduled tasks</small></article><article><label>Open tasks</label><strong>{dayTasks.length-done}</strong><small>For the selected day</small></article><article><label>All tasks</label><strong>{tasks.length}</strong><small>Saved in this browser</small></article></div>
 <div className="columns"><section className="panel schedule"><div className="panel-head"><div><h2>{view==='Day'?'Your schedule':view==='Week'?'Choose a day this week':'Choose a date'}</h2><p>Tasks are attached to their scheduled date.</p></div><button className="link" onClick={()=>{setView('Day');setDate(new Date())}}>Go to today <ArrowRight size={13}/></button></div>
 {view==='Day'?<div className="timeline">{dayTasks.length?dayTasks.map(t=><div className="task-row" key={t.id}><time>{t.time}</time><span className={'dot '+(t.done?'checked':'')}></span><div className="task"><button className={'check '+(t.done?'is-done':'')} aria-label={t.done?'Mark incomplete':'Mark complete'} onClick={()=>toggle(t.id)}>{t.done?<Check size={12}/>:<Circle size={14}/>}</button><span className="task-copy"><b className={t.done?'struck':''}>{t.title}</b><small><i className={'category '+t.category.toLowerCase()}/>{t.category}<em>·</em> {t.duration} min</small></span><button className="delete" aria-label={'Delete '+t.title} onClick={()=>remove(t.id)}><Trash2 size={13}/></button></div></div>):<div className="empty"><CalendarDays size={22}/><b>No tasks planned for this day</b><span>Add a task to give this day some structure.</span><button className="link" onClick={()=>setAdding(true)}><Plus size={13}/> Create a task</button></div>}</div>:view==='Week'?<div className="week-grid">{weekDays.map(d=>{const key=dateKey(d),list=tasks.filter(t=>t.date===key);return <button key={key} className={'week-day '+(key===selected?'chosen':'')} onClick={()=>{setDate(d);setView('Day')}}><small>{d.toLocaleDateString('en-US',{weekday:'short'})}</small><b>{d.getDate()}</b><span>{list.length} {list.length===1?'task':'tasks'}</span><i style={{width:Math.min(100,list.length*16)+'%'}}/></button>})}</div>:<><div className="week-grid month-grid">{['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map(d=><small key={d}>{d}</small>)}</div><div className="month-grid">{monthDays.map(d=>{const key=dateKey(d);return <button key={key} className={'month-day '+(d.getMonth()!==date.getMonth()?'muted ':'')+(key===selected?'chosen':'')} onClick={()=>{setDate(d);setView('Day')}}><b>{d.getDate()}</b>{taskCount(key)>0&&<span>{taskCount(key)} task{taskCount(key)>1?'s':''}</span>}</button>})}</div></>}
 <button className="add-inline" onClick={()=>setAdding(true)}><Plus size={14}/> Add a task to {selected===todayKey()?'today':'this date'}</button></section>
 <div className="right"><section className="panel intention"><div className="panel-head"><div><h2>Daily intention</h2><p>Make space for your most important work.</p></div><span className="spark">✦</span></div><blockquote>“Progress is built one focused moment at a time.”</blockquote><div className="panel-foot">● Your focus is yours to shape <span>One step at a time</span></div></section><section className="panel insight"><div className="panel-head"><div><h2>Plan with purpose</h2><p>A quick check-in with yourself.</p></div><Activity size={17} color="#419879"/></div><div className="insight-body"><div className="ring" style={{background:'conic-gradient(#6bb99a '+pct+'%,#edf0f1 0)'}}><div><b>{pct}%</b><small>complete</small></div></div><div><b>{dayTasks.length?done===dayTasks.length?'Day complete.':'You’re moving forward.':'Start with one task.'}</b><p>{dayTasks.length-done} tasks left on your selected date.</p></div></div></section><section className="import"><CloudUpload size={19}/><div><b>Bring your schedule in</b><small>Schedule-file import is a future module.</small></div><button aria-label="Import information" onClick={()=>setToast('File import is not active yet')}>↥</button></section></div></div><footer>✳ A calmer way to get things done. <span>Changes save in this browser ✦</span></footer></div></section>
 {adding&&<div className="overlay" onClick={e=>{if(e.target===e.currentTarget)setAdding(false)}}><div className="modal"><div className="modal-head"><div><small>YOUR PLAN · {selected}</small><h2>Create a task</h2></div><button aria-label="Close dialog" onClick={()=>setAdding(false)}><X size={17}/></button></div><label>What needs your attention?<input autoFocus value={title} onChange={e=>setTitle(e.target.value)} placeholder="e.g. Prepare project proposal" onKeyDown={e=>{if(e.key==='Enter')add()}}/></label><div className="form-row"><label>Start time<input type="time" value={time} onChange={e=>setTime(e.target.value)}/></label><label>Duration (minutes)<input type="number" min="5" step="5" value={duration} onChange={e=>setDuration(e.target.value)}/></label></div><label>Category<select value={category} onChange={e=>setCategory(e.target.value)}>{['Work','Personal','Planning','Build','Learning'].map(c=><option key={c}>{c}</option>)}</select></label><div className="modal-actions"><button onClick={()=>setAdding(false)}>Cancel</button><button className="primary" disabled={!title.trim()} onClick={add}><Plus size={14}/> Add task</button></div></div></div>}{toast&&<div className="toast"><CheckCircle2 size={15}/>{toast}<button onClick={()=>setToast('')}><X size={13}/></button></div>}</main>
}