import { NextRequest, NextResponse } from "next/server";
import * as XLSX from "xlsx";
import mammoth from "mammoth";
import pdf from "pdf-parse";
export const runtime = "nodejs";
type Task={title:string;date?:string;start?:string;end?:string;project?:string;description?:string};
const time24=(v:unknown):string|undefined=>{
 if(typeof v==="number"&&v>=0&&v<1){const n=Math.round(v*1440);return String(Math.floor(n/60)%24).padStart(2,"0")+":"+String(n%60).padStart(2,"0");}
 if(typeof v!=="string")return;const m=v.trim().match(/\b(\d{1,2})(?::(\d{2}))?\s*(am|pm)?\b/i);if(!m)return;
 let h=+m[1],min=+(m[2]||0);if(m[3]?.toLowerCase()==="pm"&&h<12)h+=12;if(m[3]?.toLowerCase()==="am"&&h===12)h=0;
 return h<24&&min<60?String(h).padStart(2,"0")+":"+String(min).padStart(2,"0"):undefined;
};
const dateISO=(v:unknown):string|undefined=>{if(typeof v==="number"&&v>20000&&v<80000){const d=XLSX.SSF.parse_date_code(v);return d?d.y+"-"+String(d.m).padStart(2,"0")+"-"+String(d.d).padStart(2,"0"):undefined;}if(v instanceof Date&&!isNaN(v.valueOf()))return v.toISOString().slice(0,10);if(typeof v==="string"){const d=new Date(v);if(v.trim()&&!isNaN(d.valueOf()))return d.toISOString().slice(0,10);}return;};
function parseRows(rows:unknown[][]):Task[]{if(!rows.length)return[];const h=rows[0].map(x=>String(x??"").toLowerCase());const col=(terms:string[])=>h.findIndex(x=>terms.some(t=>x.includes(t)));const ti=col(["task","activity","title","event","target"]),di=col(["date","day"]),si=col(["start","from","begin"]),ei=col(["deadline","end","until","to"]),pi=col(["project","category","course"]),ni=col(["notes","details"]);const header=ti>=0;return (header?rows.slice(1):rows).map(r=>{const title=String(r[header?ti:0]??"").trim();if(!title)return null;return{title,date:di>=0?dateISO(r[di]):undefined,start:si>=0?time24(r[si]):undefined,end:ei>=0?time24(r[ei]):undefined,project:pi>=0?String(r[pi]??"").trim():undefined,description:ni>=0?String(r[ni]??"").trim():undefined};}).filter((x):x is Task=>!!x);}
function parseText(text:string):Task[]{const out:Task[]=[];for(const line of text.split(/\r?\n/).map(x=>x.trim()).filter(Boolean)){const m=line.match(/^(.*?)\s+(\d{1,2}(?::\d{2})?\s*(?:am|pm)?)\s*(?:-|–|to)\s*(\d{1,2}(?::\d{2})?\s*(?:am|pm)?)(?:\s*[|,—]\s*(.*))?$/i);if(m)out.push({title:m[1].replace(/^[-•*\d.)\s]+/,"").trim(),start:time24(m[2]),end:time24(m[3]),description:m[4]});else{const title=line.replace(/^[-•*\d.)\s]+/,"").trim();if(title.length>3&&title.length<180)out.push({title});}}return out;}
export async function POST(req:NextRequest){try{const form=await req.formData();const file=form.get("file");if(!(file instanceof File))return NextResponse.json({error:"Choose a file first."},{status:400});if(file.size>20*1024*1024)return NextResponse.json({error:"File exceeds 20 MB."},{status:413});const name=file.name.toLowerCase(),buf=Buffer.from(await file.arrayBuffer());let tasks:Task[]=[];if(/\.(xlsx|xls|csv)$/.test(name)){const wb=XLSX.read(buf,{type:"buffer",cellDates:true});for(const s of wb.SheetNames)tasks.push(...parseRows(XLSX.utils.sheet_to_json<unknown[]>(wb.Sheets[s],{header:1,raw:true})));}else if(name.endsWith(".docx")){tasks=parseText((await mammoth.extractRawText({buffer:buf})).value);}else if(name.endsWith(".pdf")){tasks=parseText((await pdf(buf)).text);}else return NextResponse.json({error:"Supported formats: XLSX, XLS, CSV, DOCX, PDF."},{status:415});return NextResponse.json({tasks:tasks.slice(0,500),count:tasks.length});}catch(e){return NextResponse.json({error:e instanceof Error?e.message:"Extraction failed."},{status:422});}}
